import type { WeatherState } from "../../simulation/core/types";

export type WorldReactionKind = "work" | "ready" | "trade" | "homecoming" | "milestone";

interface WorldReactionTuning {
  durationSeconds: number;
  radiusMeters: number;
  bodyTurnThreshold: number;
  nodRadians: number;
}

const REACTION_TUNING: Readonly<Record<WorldReactionKind, WorldReactionTuning>> = {
  // Routine work gets a glance, not a staged crowd turn.
  work: { durationSeconds: 2.4, radiusMeters: 9, bodyTurnThreshold: 1.1, nodRadians: 0.018 },
  ready: { durationSeconds: 3, radiusMeters: 11, bodyTurnThreshold: 0.86, nodRadians: 0.022 },
  trade: { durationSeconds: 3.2, radiusMeters: 13, bodyTurnThreshold: 0.7, nodRadians: 0.026 },
  homecoming: { durationSeconds: 4.6, radiusMeters: 23, bodyTurnThreshold: 0.34, nodRadians: 0.038 },
  milestone: { durationSeconds: 4, radiusMeters: 16, bodyTurnThreshold: 0.42, nodRadians: 0.034 }
};

interface WorldReactionPulse {
  kind: WorldReactionKind;
  x: number;
  z: number;
  startedAtSeconds: number;
}

export interface SocialReactionSample {
  /** 0..1 attention weight used for head and body orientation. */
  attention: number;
  /** Strong reactions invite the whole body to turn instead of only the head. */
  turnBody: boolean;
  /** Small root-space bow/nod. It is additive to authored animation. */
  nodRadians: number;
  kind: WorldReactionKind | null;
  /** World point that caused the response; people look here, not through it. */
  targetX: number;
  targetZ: number;
}

export interface WeatherPostureSample {
  pitchRadians: number;
  rollRadians: number;
}

const EMPTY_REACTION: SocialReactionSample = {
  attention: 0,
  turnBody: false,
  nodRadians: 0,
  kind: null,
  targetX: 0,
  targetZ: 0
};

function smoothstep01(value: number): number {
  const t = Math.max(0, Math.min(1, value));
  return t * t * (3 - 2 * t);
}

function pulseEnvelope(progress: number): number {
  const attack = smoothstep01(progress / 0.18);
  const release = 1 - smoothstep01((progress - 0.52) / 0.48);
  return Math.max(0, Math.min(1, attack * release));
}

/**
 * Short-lived, render-only attention generated by committed world events.
 * Pulses are deliberately local and bounded: ordinary work earns a glance,
 * while a cargo-bearing harbor return can turn a small group toward the player.
 */
export class SocialReactionPresentation {
  private readonly pulses: WorldReactionPulse[] = [];

  public trigger(kind: WorldReactionKind, x: number, z: number, timeSeconds: number): void {
    this.pulses.push({ kind, x, z, startedAtSeconds: timeSeconds });
    if (this.pulses.length > 12) this.pulses.splice(0, this.pulses.length - 12);
  }

  public sample(x: number, z: number, timeSeconds: number, reducedMotion: boolean): SocialReactionSample {
    let best: SocialReactionSample = EMPTY_REACTION;
    for (let index = this.pulses.length - 1; index >= 0; index -= 1) {
      const pulse = this.pulses[index];
      const tuning = REACTION_TUNING[pulse.kind];
      const elapsed = timeSeconds - pulse.startedAtSeconds;
      if (elapsed >= tuning.durationSeconds) {
        this.pulses.splice(index, 1);
        continue;
      }
      if (elapsed < 0) continue;
      const distance = Math.hypot(x - pulse.x, z - pulse.z);
      if (distance >= tuning.radiusMeters) continue;
      const distanceWeight = smoothstep01(1 - distance / tuning.radiusMeters);
      const progress = elapsed / tuning.durationSeconds;
      const attention = distanceWeight * pulseEnvelope(progress);
      if (attention <= best.attention) continue;
      const nodMotion = reducedMotion ? 0 : Math.sin(progress * Math.PI * 3) * tuning.nodRadians * attention;
      best = {
        attention,
        turnBody: attention >= tuning.bodyTurnThreshold,
        nodRadians: nodMotion,
        kind: pulse.kind,
        targetX: pulse.x,
        targetZ: pulse.z
      };
    }
    return best;
  }

  public clear(): void {
    this.pulses.length = 0;
  }
}

/**
 * A restrained presentation posture for exposed people. It reads the shipped
 * weather snapshot and never invents wetness, warmth, stamina, or another
 * canonical condition. Reduced motion retains a smaller static weather lean.
 */
export function sampleWeatherPosture(
  weather: Pick<WeatherState, "windDirectionDeg" | "windSpeed" | "precipitation">,
  facingRadians: number,
  timeSeconds: number,
  reducedMotion: boolean,
  phase = 0
): WeatherPostureSample {
  const wind = smoothstep01((weather.windSpeed - 4) / 14);
  const rain = smoothstep01(weather.precipitation);
  const strength = Math.max(wind, rain * 0.72);
  if (strength <= 0.001) return { pitchRadians: 0, rollRadians: 0 };

  const windHeading = weather.windDirectionDeg * Math.PI / 180;
  const relative = windHeading - facingRadians;
  const motionScale = reducedMotion ? 0.48 : 1;
  const gust = reducedMotion ? 1 : 0.88 + Math.sin(timeSeconds * 0.72 + phase) * 0.12;
  const hunch = rain * 0.018;
  return {
    pitchRadians: (hunch - Math.cos(relative) * wind * 0.034) * strength * motionScale * gust,
    rollRadians: Math.sin(relative) * wind * 0.032 * strength * motionScale * gust
  };
}
