/**
 * Generates the typed UI atlas lookup from assets/ui/ui-atlas.manifest.json.
 *
 *   node tools/ui/codegen.mjs
 *   node tools/ui/codegen.mjs --check
 *
 * Keeping the maps generated means a sprite cannot exist in the manifest but be
 * unreachable from code, or be referenced by code without a file behind it.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { loadManifest } from "./slice-sheet.mjs";

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(SCRIPT_PATH), "../..");
const OUTPUT_PATH = path.join(ROOT, "src/ui/chrome/uiAtlas.generated.ts");

function pascalCase(value) {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

export function renderGeneratedAtlas(manifest) {
  const byFamily = new Map(Object.keys(manifest.families).map((family) => [family, []]));
  for (const sheet of manifest.sheets) {
    for (const sprite of sheet.sprites) byFamily.get(sheet.family).push(sprite);
  }

  const lines = [
    "// This file is generated by `npm run ui:codegen`. Do not edit it by hand.",
    "// Source of truth: assets/ui/ui-atlas.manifest.json",
    "",
    `const ATLAS = ${JSON.stringify(`/${manifest.runtimeDir.replace(/^public\//, "")}`)};`,
    ""
  ];

  for (const [family, meta] of Object.entries(manifest.families)) {
    const sprites = byFamily.get(family);
    if (sprites.length === 0) continue;
    lines.push(`/** ${meta.doc} */`);
    lines.push(`export const ${meta.export} = {`);
    for (const sprite of sprites) {
      lines.push(`  ${JSON.stringify(sprite.id)}: \`\${ATLAS}/${sprite.file}\`,`);
    }
    lines.push("} as const;");
    lines.push("");
    lines.push(`export type ${pascalCase(family)}SpriteKey = keyof typeof ${meta.export};`);
    lines.push("");
  }

  for (const texture of manifest.textures ?? []) {
    const name = `UI_${texture.id.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase()}`;
    lines.push(`/** ${texture.doc} */`);
    lines.push(`export const ${name} = \`\${ATLAS}/${texture.file}\`;`);
    lines.push("");
  }

  const total = manifest.sheets.reduce((sum, sheet) => sum + sheet.sprites.length, 0);
  lines.push(`export const UI_ATLAS_SPRITE_COUNT = ${total};`);
  lines.push("");

  return lines.join("\n");
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const manifest = loadManifest();
  const output = renderGeneratedAtlas(manifest);
  const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, "utf8") : null;

  if (checkOnly) {
    if (current !== output) {
      throw new Error(`Generated UI atlas is stale: ${OUTPUT_PATH}. Run npm run ui:codegen.`);
    }
    console.log("[NEVA UI] Atlas adapter is up to date");
    return;
  }

  if (current !== output) {
    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(OUTPUT_PATH, output);
    console.log(`[NEVA UI] Wrote ${path.relative(ROOT, OUTPUT_PATH)}`);
  } else {
    console.log("[NEVA UI] Atlas adapter unchanged");
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === SCRIPT_PATH) {
  try {
    main();
  } catch (error) {
    console.error(`[NEVA UI] ${error.message}`);
    process.exitCode = 1;
  }
}
