// Generated by tools/world/mainlandRoadNetwork.ts (npm run world:plan-roads). Do not edit.
// Every mainland road in survey order: trunks before the roads that branch from them.
// A knot shared by two roads is a junction; a third number is a retained datum.

export const MAINLAND_ROAD_NETWORK_FINGERPRINT = "af27c513";

export const MAINLAND_ROAD_NETWORK: readonly {
  readonly id: string;
  readonly kind: "arterial" | "lane" | "trail";
  readonly knots: readonly (readonly [number, number] | readonly [number, number, number])[];
}[] = [
  { id: "mainland-farm-pinewatch", kind: "arterial", knots: [[-87, -60, 1.2], [-145, -48, 3], [-190, -45, 4], [-230, -28, 5.4], [-246, -20], [-270, -20], [-302, -4], [-334, 12],
      [-362, 40], [-395, 55, 6]] },
  { id: "mainland-village-highridge", kind: "arterial", knots: [[70, -68, 6.3], [62, -88, 6.3], [72, -104, 7.5], [100, -115], [103, -143], [91, -175], [84, -212], [63, -246],
      [22, -278], [-27, -283], [-72, -302], [-78, -300], [-102, -308], [-122, -300], [-182, -300], [-234, -336],
      [-290, -364], [-340, -365, 19.6]] },
  { id: "mainland-reedhaven-landing", kind: "lane", knots: [[-565, 340, 2.4], [-537, 341, 2.2], [-514, 336, 1.6], [-489, 333, 0.45]] },
  { id: "mainland-pinewatch-landing", kind: "lane", knots: [[-395, 55, 6], [-386, 75, 3], [-384, 94, 0.45]] },
  { id: "mainland-pinewatch-reedhaven", kind: "arterial", knots: [[-395, 55, 6], [-402, 48], [-450, 48], [-498, 24], [-534, -12], [-562, -40], [-578, -72], [-578, -88],
      [-566, -112], [-530, -144], [-522, -160], [-522, -204], [-550, -244], [-566, -252], [-598, -244], [-626, -208],
      [-626, -164], [-619.8, -153], [-606, -132], [-618, -100], [-618, -60], [-590, -8], [-570, 32], [-570, 80],
      [-554, 112], [-554, 152], [-542, 176], [-542, 212], [-526, 244], [-526, 300], [-542, 332], [-537, 341, 2.2]] },
  { id: "mainland-pinewatch-highridge", kind: "arterial", knots: [[-402, 48], [-398, 40], [-398, -8], [-398, -52], [-374, -100], [-374, -148], [-374, -196], [-374, -244],
      [-374, -292], [-359.5, -321.8], [-354, -332], [-340, -365, 19.6]] },
  { id: "mainland-highridge-adit-road", kind: "lane", knots: [[-538.5, -403], [-522, -396], [-486, -360], [-446, -340], [-394, -340], [-370, -328], [-359.5, -321.8]] },
  { id: "mainland-lake-ice-house-road", kind: "lane", knots: [[-624.7, -140.3], [-626, -148], [-619.8, -153]] }
];
