// Generated by tools/world/mainlandRoadRouter.ts (npm run world:route-roads). Do not edit.
// Interior knots of every routed leg in MAINLAND_ROUTE_PLANS, in plan order.

export const MAINLAND_ROUTE_FINGERPRINT = "b7fdc0c1";

export const MAINLAND_ROUTED_LEGS: Readonly<Record<string, readonly (readonly (readonly [number, number])[])[]>> = {
  "mainland-farm-pinewatch": [
    [[-287, 0], [-343, 28]]
  ],
  "mainland-village-highridge": [
    [[-108, -309], [-120, -301], [-152, -301], [-184, -301], [-228, -333], [-260, -349], [-292, -365]]
  ],
  "mainland-pinewatch-highridge": [
    [[-393, -4], [-393, -60], [-393, -116], [-409, -148]],
    [[-401, -229], [-377, -277], [-361, -325]]
  ],
  "mainland-forest-road": [
    [[-464, -185], [-492, -241], [-508, -257], [-548, -277], [-580, -277], [-612, -277], [-656, -257]],
    [[-672, -173], [-664, -137], [-664, -89], [-660, -45], [-636, 3], [-616, 43], [-616, 75], [-592, 123],
      [-592, 159], [-592, 191], [-624, 243]],
    [[-593, 314]]
  ],
  "mainland-forest-lake": [
    [[-680, -189], [-656, -141], [-632, -121], [-624, -125], [-624, -165]]
  ],
  "mainland-marsh-bank": [
    [[-601, 266], [-569, 250], [-545, 234], [-537, 218]]
  ],
  "mainland-highridge-overlook": [
    [[-378, -364], [-418, -344], [-462, -344], [-506, -372]]
  ]
};
