// Generated by tools/world/mainlandRoadRouter.ts (npm run world:route-roads). Do not edit.
// Interior knots of every routed leg in MAINLAND_ROUTE_PLANS, in plan order.

export const MAINLAND_ROUTE_FINGERPRINT = "3a72b364";

export const MAINLAND_ROUTED_LEGS: Readonly<Record<string, readonly (readonly (readonly [number, number])[])[]>> = {
  "mainland-farm-pinewatch": [
    [[-287, 0], [-343, 32]]
  ],
  "mainland-village-highridge": [
    [[-108, -309], [-120, -301], [-152, -301], [-184, -301], [-228, -333], [-260, -349], [-292, -365]]
  ],
  "mainland-pinewatch-highridge": [
    [[-393, -4], [-393, -60], [-393, -116], [-409, -148]],
    [[-405, -221], [-405, -237], [-381, -285], [-361, -325]]
  ],
  "mainland-forest-road": [
    [[-460, -201], [-488, -257], [-520, -289], [-568, -313], [-600, -313], [-624, -301], [-660, -265]],
    [[-672, -173], [-664, -137], [-664, -101], [-664, -65], [-636, -9], [-612, 39], [-612, 75], [-588, 123],
      [-588, 159], [-588, 191], [-608, 231], [-624, 263]],
    [[-593, 314]]
  ],
  "mainland-forest-lake": [
    [[-672, -165], [-660, -141], [-632, -121], [-624, -125], [-624, -165]]
  ],
  "mainland-marsh-bank": [
    [[-589, 258], [-561, 230], [-537, 182]]
  ],
  "mainland-highridge-overlook": [
    [[-378, -364], [-418, -344], [-458, -344], [-502, -368]]
  ]
};
