import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { validateCatalog } from "../blender/cli.mjs";

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(SCRIPT_PATH), "../..");
const OUTPUT_PATH = path.join(ROOT, "src/render/assets/AssetCatalog.generated.ts");

function constantName(assetId) {
  const name = assetId.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase();
  if (!/^[A-Z][A-Z0-9_]*$/.test(name)) {
    throw new Error(`Cannot derive a TypeScript constant name from asset ID ${assetId}`);
  }
  return name;
}

function renderGeneratedCatalog(catalog) {
  const assets = catalog.assets;
  const constants = new Map();
  for (const asset of assets) {
    const name = constantName(asset.id);
    const previous = constants.get(name);
    if (previous && previous !== asset.id) {
      throw new Error(`Asset IDs ${previous} and ${asset.id} collide as ${name}`);
    }
    constants.set(name, asset.id);
  }

  const families = [...new Set(assets.map((asset) => asset.family))].sort();
  const byFamily = new Map(families.map((family) => [family, []]));
  for (const asset of assets) byFamily.get(asset.family).push(asset);

  return [
    "// This file is generated by `npm run art:codegen`. Do not edit it by hand.",
    "",
    "export const ASSET_IDS = {",
    ...assets.map((asset) => `  ${constantName(asset.id)}: ${JSON.stringify(asset.id)},`),
    "} as const;",
    "",
    "export type AssetId = (typeof ASSET_IDS)[keyof typeof ASSET_IDS];",
    "",
    `export const ASSET_FAMILIES = ${JSON.stringify(families)} as const;`,
    "export type AssetFamily = (typeof ASSET_FAMILIES)[number];",
    "",
    "export const ASSET_IDS_BY_FAMILY = {",
    ...families.map((family) => [
      `  ${JSON.stringify(family)}: [`,
      ...byFamily.get(family).map((asset) => `    ASSET_IDS.${constantName(asset.id)},`),
      "  ],"
    ]).flat(),
    "} as const satisfies { readonly [family in AssetFamily]: readonly AssetId[] };",
    "",
  ].join("\n");
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const { catalog } = validateCatalog();
  const output = renderGeneratedCatalog(catalog);
  const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, "utf8") : null;

  if (checkOnly) {
    if (current !== output) {
      throw new Error(`Generated catalog adapter is stale: ${OUTPUT_PATH}. Run npm run art:codegen.`);
    }
    console.log(`[NEVA CODEGEN] Catalog adapter is up to date (${catalog.assets.length} assets)`);
    return;
  }

  if (current !== output) {
    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(OUTPUT_PATH, output);
    console.log(`[NEVA CODEGEN] Wrote ${OUTPUT_PATH} (${catalog.assets.length} assets)`);
  } else {
    console.log(`[NEVA CODEGEN] Catalog adapter unchanged (${catalog.assets.length} assets)`);
  }
}

export { constantName, renderGeneratedCatalog };

if (process.argv[1] && path.resolve(process.argv[1]) === SCRIPT_PATH) {
  try {
    main();
  } catch (error) {
    console.error(`[NEVA CODEGEN] ${error.stack ?? error.message}`);
    process.exitCode = 1;
  }
}
