// src/content/fish.ts

import { FishBehaviorProfile, FishSpeciesDefinition } from "./types";

export const FISH_BEHAVIOR_PROFILES: Record<string, FishBehaviorProfile> = {
  "profile.carp": {
    id: "profile.carp",
    baseStamina: 40,
    behaviorWeights: {
      "rest": 0.45,
      "run-left": 0.15,
      "run-right": 0.15,
      "dive": 0.15,
      "surface": 0.05,
      "burst": 0.03,
      "shake": 0.02
    },
    minBehaviorDurationSeconds: 2.0,
    maxBehaviorDurationSeconds: 5.0,
    burstStrength: 10,
    directionalForce: 12,
    tensionSensitivity: 0.8,
    escapeSlackSeconds: 4.0
  },
  "profile.trout": {
    id: "profile.trout",
    baseStamina: 60,
    behaviorWeights: {
      "rest": 0.20,
      "run-left": 0.25,
      "run-right": 0.25,
      "surface": 0.15,
      "burst": 0.10,
      "shake": 0.05,
      "dive": 0.00
    },
    minBehaviorDurationSeconds: 1.2,
    maxBehaviorDurationSeconds: 3.0,
    burstStrength: 18,
    directionalForce: 18,
    tensionSensitivity: 1.1,
    escapeSlackSeconds: 2.5
  },
  "profile.perch": {
    id: "profile.perch",
    baseStamina: 30,
    behaviorWeights: {
      "rest": 0.35,
      "run-left": 0.20,
      "run-right": 0.20,
      "shake": 0.15,
      "surface": 0.05,
      "dive": 0.05,
      "burst": 0.00
    },
    minBehaviorDurationSeconds: 1.0,
    maxBehaviorDurationSeconds: 2.5,
    burstStrength: 8,
    directionalForce: 10,
    tensionSensitivity: 0.7,
    escapeSlackSeconds: 4.5
  },
  "profile.catfish": {
    id: "profile.catfish",
    baseStamina: 90,
    behaviorWeights: {
      "dive": 0.45,
      "rest": 0.25,
      "run-left": 0.15,
      "run-right": 0.15,
      "burst": 0.00,
      "surface": 0.00,
      "shake": 0.00
    },
    minBehaviorDurationSeconds: 2.5,
    maxBehaviorDurationSeconds: 6.0,
    burstStrength: 12,
    directionalForce: 25,
    tensionSensitivity: 1.3,
    escapeSlackSeconds: 3.5
  },
  "profile.pike": {
    id: "profile.pike",
    baseStamina: 75,
    behaviorWeights: {
      "burst": 0.30,
      "run-left": 0.25,
      "run-right": 0.25,
      "rest": 0.15,
      "shake": 0.05,
      "dive": 0.00,
      "surface": 0.00
    },
    minBehaviorDurationSeconds: 1.0,
    maxBehaviorDurationSeconds: 2.5,
    burstStrength: 28,
    directionalForce: 22,
    tensionSensitivity: 1.4,
    escapeSlackSeconds: 2.0
  },
  "profile.arowana": {
    id: "profile.arowana",
    baseStamina: 110,
    behaviorWeights: {
      "surface": 0.35,
      "burst": 0.25,
      "run-left": 0.15,
      "run-right": 0.15,
      "rest": 0.10,
      "shake": 0.00,
      "dive": 0.00
    },
    minBehaviorDurationSeconds: 0.8,
    maxBehaviorDurationSeconds: 2.0,
    burstStrength: 32,
    directionalForce: 26,
    tensionSensitivity: 1.6,
    escapeSlackSeconds: 1.8
  },
  "profile.mackerel": {
    id: "profile.mackerel",
    baseStamina: 45,
    behaviorWeights: {
      "run-left": 0.30,
      "run-right": 0.30,
      "rest": 0.25,
      "surface": 0.10,
      "burst": 0.05,
      "dive": 0.00,
      "shake": 0.00
    },
    minBehaviorDurationSeconds: 1.0,
    maxBehaviorDurationSeconds: 3.0,
    burstStrength: 14,
    directionalForce: 15,
    tensionSensitivity: 0.9,
    escapeSlackSeconds: 3.0
  },
  "profile.tuna": {
    id: "profile.tuna",
    baseStamina: 140,
    behaviorWeights: {
      "run-left": 0.35,
      "run-right": 0.35,
      "burst": 0.15,
      "dive": 0.10,
      "rest": 0.05,
      "surface": 0.00,
      "shake": 0.00
    },
    minBehaviorDurationSeconds: 2.0,
    maxBehaviorDurationSeconds: 5.0,
    burstStrength: 30,
    directionalForce: 32,
    tensionSensitivity: 1.5,
    escapeSlackSeconds: 2.0
  },
  "profile.sturgeon": {
    id: "profile.sturgeon",
    baseStamina: 180,
    behaviorWeights: {
      "dive": 0.50,
      "rest": 0.20,
      "run-left": 0.15,
      "run-right": 0.15,
      "burst": 0.00,
      "surface": 0.00,
      "shake": 0.00
    },
    minBehaviorDurationSeconds: 3.0,
    maxBehaviorDurationSeconds: 7.0,
    burstStrength: 20,
    directionalForce: 38,
    tensionSensitivity: 1.6,
    escapeSlackSeconds: 3.0
  },
  "profile.sailfish": {
    id: "profile.sailfish",
    baseStamina: 160,
    behaviorWeights: {
      "burst": 0.35,
      "surface": 0.25,
      "run-left": 0.20,
      "run-right": 0.15,
      "rest": 0.05,
      "dive": 0.00,
      "shake": 0.00
    },
    minBehaviorDurationSeconds: 0.8,
    maxBehaviorDurationSeconds: 2.2,
    burstStrength: 38,
    directionalForce: 36,
    tensionSensitivity: 1.8,
    escapeSlackSeconds: 1.5
  },
  "profile.swordfish": {
    id: "profile.swordfish",
    baseStamina: 190,
    behaviorWeights: {
      "burst": 0.30,
      "run-left": 0.25,
      "run-right": 0.25,
      "dive": 0.15,
      "rest": 0.05,
      "surface": 0.00,
      "shake": 0.00
    },
    minBehaviorDurationSeconds: 1.2,
    maxBehaviorDurationSeconds: 3.0,
    burstStrength: 42,
    directionalForce: 40,
    tensionSensitivity: 1.9,
    escapeSlackSeconds: 1.5
  },
  "profile.blue_marlin": {
    id: "profile.blue_marlin",
    baseStamina: 240,
    behaviorWeights: {
      "burst": 0.35,
      "surface": 0.25,
      "run-left": 0.20,
      "run-right": 0.15,
      "dive": 0.05,
      "rest": 0.00,
      "shake": 0.00
    },
    minBehaviorDurationSeconds: 1.0,
    maxBehaviorDurationSeconds: 3.0,
    burstStrength: 48,
    directionalForce: 45,
    tensionSensitivity: 2.2,
    escapeSlackSeconds: 1.2
  }
};

export const FISH_SPECIES: Record<string, FishSpeciesDefinition> = {
  // Freshwater (6)
  "fish.carp": {
    id: "fish.carp",
    name: "Common Carp",
    habitats: ["river", "lake"],
    seasons: ["spring", "summer", "autumn", "winter"],
    timeWindows: ["dawn", "day", "dusk", "night"],
    weatherPreferences: ["clear", "cloudy", "light-rain", "windy"],
    weightKg: { min: 2.5, average: 5.0, max: 12.0 },
    baseMarketValue: 35,
    rarityWeight: 100,
    behaviorProfileId: "profile.carp",
    minimumRodClass: "willow",
    cargoClass: "small",
    baseDecayRatePerMinute: 0.12,
    isSportFish: false,
    minigameBehavior: "smooth",
    minigameDifficulty: 18,
    tags: ["freshwater", "basic", "bottom-feeder"]
  },
  "fish.trout": {
    id: "fish.trout",
    name: "Rainbow Trout",
    habitats: ["river", "lake"],
    seasons: ["spring", "summer", "autumn", "winter"],
    timeWindows: ["dawn", "dusk", "day"],
    weatherPreferences: ["light-rain", "cloudy", "fog"],
    weightKg: { min: 1.2, average: 3.2, max: 7.5 },
    baseMarketValue: 50,
    rarityWeight: 80,
    behaviorProfileId: "profile.trout",
    minimumRodClass: "willow",
    cargoClass: "small",
    baseDecayRatePerMinute: 0.15,
    isSportFish: true,
    minigameBehavior: "dart",
    minigameDifficulty: 52,
    tags: ["freshwater", "sport", "active"]
  },
  "fish.perch": {
    id: "fish.perch",
    name: "River Perch",
    habitats: ["river"],
    seasons: ["spring", "summer", "autumn", "winter"],
    timeWindows: ["dawn", "day", "dusk", "night"],
    weatherPreferences: ["clear", "cloudy", "windy", "light-rain", "fog"],
    weightKg: { min: 0.4, average: 1.0, max: 2.2 },
    baseMarketValue: 15,
    rarityWeight: 120,
    behaviorProfileId: "profile.perch",
    minimumRodClass: "willow",
    cargoClass: "small",
    baseDecayRatePerMinute: 0.18,
    isSportFish: false, // Catchable via basic fishing
    minigameBehavior: "mixed",
    minigameDifficulty: 30,
    tags: ["freshwater", "basic"]
  },
  "fish.catfish": {
    id: "fish.catfish",
    name: "Channel Catfish",
    habitats: ["river", "lake"],
    seasons: ["summer", "autumn"],
    timeWindows: ["dusk", "night", "dawn"],
    weatherPreferences: ["cloudy", "heavy-rain", "storm"],
    weightKg: { min: 4.0, average: 10.0, max: 28.0 },
    baseMarketValue: 75,
    rarityWeight: 50,
    behaviorProfileId: "profile.catfish",
    minimumRodClass: "river",
    cargoClass: "medium",
    baseDecayRatePerMinute: 0.10,
    isSportFish: true,
    minigameBehavior: "sinker",
    minigameDifficulty: 58,
    tags: ["freshwater", "sport", "heavy"]
  },
  "fish.pike": {
    id: "fish.pike",
    name: "Northern Pike",
    habitats: ["lake"],
    seasons: ["autumn", "winter", "spring"],
    timeWindows: ["dawn", "day"],
    weatherPreferences: ["fog", "cloudy", "windy"],
    weightKg: { min: 3.0, average: 7.0, max: 18.0 },
    baseMarketValue: 90,
    rarityWeight: 40,
    behaviorProfileId: "profile.pike",
    minimumRodClass: "river",
    cargoClass: "medium",
    baseDecayRatePerMinute: 0.14,
    isSportFish: true,
    minigameBehavior: "dart",
    minigameDifficulty: 65,
    tags: ["freshwater", "sport", "predator"]
  },
  "fish.arowana": {
    id: "fish.arowana",
    name: "Golden Arowana",
    habitats: ["lake"],
    seasons: ["summer"],
    timeWindows: ["dusk", "night"],
    weatherPreferences: ["clear", "fog"],
    weightKg: { min: 4.5, average: 8.5, max: 16.0 },
    baseMarketValue: 220,
    rarityWeight: 15,
    behaviorProfileId: "profile.arowana",
    minimumRodClass: "heavy-sport",
    cargoClass: "medium",
    baseDecayRatePerMinute: 0.16,
    isSportFish: true,
    minigameBehavior: "mixed",
    minigameDifficulty: 70,
    tags: ["freshwater", "sport", "rare", "prized"]
  },

  // Saltwater (6)
  "fish.mackerel": {
    id: "fish.mackerel",
    name: "Atlantic Mackerel",
    habitats: ["coast"],
    seasons: ["spring", "summer", "autumn", "winter"],
    timeWindows: ["day", "dawn", "dusk"],
    weatherPreferences: ["clear", "windy"],
    weightKg: { min: 0.5, average: 1.2, max: 2.8 },
    baseMarketValue: 18,
    rarityWeight: 110,
    behaviorProfileId: "profile.mackerel",
    minimumRodClass: "willow",
    cargoClass: "small",
    baseDecayRatePerMinute: 0.20,
    isSportFish: false,
    minigameBehavior: "floater",
    minigameDifficulty: 38,
    tags: ["saltwater", "basic", "coastal"]
  },
  "fish.tuna": {
    id: "fish.tuna",
    name: "Yellowfin Tuna",
    habitats: ["coast", "offshore"],
    seasons: ["summer", "autumn"],
    timeWindows: ["dawn", "day", "dusk"],
    weatherPreferences: ["clear", "windy", "light-rain"],
    weightKg: { min: 15.0, average: 35.0, max: 80.0 },
    baseMarketValue: 160,
    rarityWeight: 45,
    behaviorProfileId: "profile.tuna",
    minimumRodClass: "heavy-sport",
    cargoClass: "medium",
    baseDecayRatePerMinute: 0.12,
    isSportFish: true,
    minigameBehavior: "smooth",
    minigameDifficulty: 68,
    tags: ["saltwater", "sport", "pelagic"]
  },
  "fish.sturgeon": {
    id: "fish.sturgeon",
    name: "White Sturgeon",
    habitats: ["coast"],
    seasons: ["autumn", "winter", "spring"],
    timeWindows: ["night", "dawn"],
    weatherPreferences: ["fog", "heavy-rain"],
    weightKg: { min: 25.0, average: 60.0, max: 150.0 },
    baseMarketValue: 240,
    rarityWeight: 25,
    behaviorProfileId: "profile.sturgeon",
    minimumRodClass: "heavy-sport",
    cargoClass: "large",
    baseDecayRatePerMinute: 0.08,
    isSportFish: true,
    minigameBehavior: "sinker",
    minigameDifficulty: 75,
    tags: ["saltwater", "sport", "ancient", "heavy"]
  },
  "fish.sailfish": {
    id: "fish.sailfish",
    name: "Pacific Sailfish",
    habitats: ["offshore"],
    seasons: ["summer"],
    timeWindows: ["day", "dusk"],
    weatherPreferences: ["clear", "windy"],
    weightKg: { min: 20.0, average: 45.0, max: 95.0 },
    baseMarketValue: 280,
    rarityWeight: 20,
    behaviorProfileId: "profile.sailfish",
    minimumRodClass: "offshore",
    cargoClass: "large",
    baseDecayRatePerMinute: 0.15,
    isSportFish: true,
    minigameBehavior: "floater",
    minigameDifficulty: 80,
    tags: ["saltwater", "sport", "fast", "trophy"]
  },
  "fish.swordfish": {
    id: "fish.swordfish",
    name: "Broadbill Swordfish",
    habitats: ["offshore"],
    seasons: ["autumn", "winter"],
    timeWindows: ["dusk", "night", "dawn"],
    weatherPreferences: ["storm", "fog", "windy"],
    weightKg: { min: 30.0, average: 75.0, max: 180.0 },
    baseMarketValue: 340,
    rarityWeight: 15,
    behaviorProfileId: "profile.swordfish",
    minimumRodClass: "offshore",
    cargoClass: "large",
    baseDecayRatePerMinute: 0.11,
    isSportFish: true,
    minigameBehavior: "sinker",
    minigameDifficulty: 85,
    tags: ["saltwater", "sport", "deep-sea", "trophy"]
  },
  "fish.blue_marlin": {
    id: "fish.blue_marlin",
    name: "Blue Marlin",
    habitats: ["offshore"],
    seasons: ["summer", "autumn"],
    timeWindows: ["dawn", "day"],
    weatherPreferences: ["clear", "windy", "storm"],
    weightKg: { min: 60.0, average: 140.0, max: 320.0 },
    baseMarketValue: 480,
    rarityWeight: 8,
    behaviorProfileId: "profile.blue_marlin",
    minimumRodClass: "master",
    cargoClass: "gargantuan",
    baseDecayRatePerMinute: 0.10,
    isSportFish: true,
    minigameBehavior: "dart",
    minigameDifficulty: 90,
    tags: ["saltwater", "sport", "apex", "legendary"]
  }
};
