// This file is generated by `npm run ui:codegen`. Do not edit it by hand.
// Source of truth: assets/ui/ui-atlas.manifest.json

const ATLAS = "/assets/ui/atlas";

/** Wayfarer HUD paintings: pewter, leather, paper and equipment. */
export const UI_TIDEBOOK = {
  "quest-panel": `${ATLAS}/tidebook-quest-panel.png`,
  "tool-plaque": `${ATLAS}/tidebook-tool-plaque.png`,
  "tool-plaque-selected": `${ATLAS}/tidebook-tool-plaque-selected.png`,
  "clock-face": `${ATLAS}/tidebook-clock-face.png`,
  "calendar-tag": `${ATLAS}/tidebook-calendar-tag.png`,
  "purse-tag": `${ATLAS}/tidebook-purse-tag.png`,
  "label-paper": `${ATLAS}/tidebook-label-paper.png`,
  "navigation-rail": `${ATLAS}/tidebook-navigation-rail.png`,
  "sea-dial": `${ATLAS}/tidebook-sea-dial.png`,
  "pointer": `${ATLAS}/tidebook-pointer.png`,
  "meter-frame": `${ATLAS}/tidebook-meter-frame.png`,
  "hoe": `${ATLAS}/tidebook-hoe.png`,
  "seeds": `${ATLAS}/tidebook-seeds.png`,
  "water": `${ATLAS}/tidebook-water.png`,
  "rod": `${ATLAS}/tidebook-rod.png`,
  "harvest": `${ATLAS}/tidebook-harvest.png`,
  "satchel": `${ATLAS}/tidebook-satchel.png`,
  "journal": `${ATLAS}/tidebook-journal.png`,
  "map": `${ATLAS}/tidebook-map.png`,
} as const;

export type TidebookSpriteKey = keyof typeof UI_TIDEBOOK;

/** Catchable species, used in HUD cargo, journal, market and both fishing modes. */
export const UI_FISH = {
  "fish.carp": `${ATLAS}/fish-carp.png`,
  "fish.trout": `${ATLAS}/fish-trout.png`,
  "fish.perch": `${ATLAS}/fish-perch.png`,
  "fish.catfish": `${ATLAS}/fish-catfish.png`,
  "fish.pike": `${ATLAS}/fish-pike.png`,
  "fish.arowana": `${ATLAS}/fish-arowana.png`,
  "fish.mackerel": `${ATLAS}/fish-mackerel.png`,
  "fish.tuna": `${ATLAS}/fish-tuna.png`,
  "fish.sturgeon": `${ATLAS}/fish-sturgeon.png`,
  "fish.sailfish": `${ATLAS}/fish-sailfish.png`,
  "fish.swordfish": `${ATLAS}/fish-swordfish.png`,
  "fish.blue_marlin": `${ATLAS}/fish-blue_marlin.png`,
  "fish.sardine": `${ATLAS}/fish-sardine.png`,
  "fish.sea_bream": `${ATLAS}/fish-sea_bream.png`,
  "fish.amberjack": `${ATLAS}/fish-amberjack.png`,
} as const;

export type FishSpriteKey = keyof typeof UI_FISH;

/** Plantable seed stock shown in the seed bar, inventory and market stall. */
export const UI_SEEDS = {
  "seed.wheat": `${ATLAS}/seed-wheat.png`,
  "seed.barley": `${ATLAS}/seed-barley.png`,
  "seed.corn": `${ATLAS}/seed-corn.png`,
  "seed.tomato": `${ATLAS}/seed-tomato.png`,
  "seed.potato": `${ATLAS}/seed-potato.png`,
  "seed.carrot": `${ATLAS}/seed-carrot.png`,
  "seed.flax": `${ATLAS}/seed-flax.png`,
  "seed.apple_sapling": `${ATLAS}/seed-apple_sapling.png`,
  "seed.sunflower": `${ATLAS}/seed-sunflower.png`,
  "seed.olive_pit": `${ATLAS}/seed-olive_pit.png`,
} as const;

export type SeedSpriteKey = keyof typeof UI_SEEDS;

/** Harvested crop goods carried in inventory and traded at market. */
export const UI_PRODUCE = {
  "produce.wheat": `${ATLAS}/produce-wheat.png`,
  "produce.barley": `${ATLAS}/produce-barley.png`,
  "produce.corn": `${ATLAS}/produce-corn.png`,
  "produce.tomato": `${ATLAS}/produce-tomato.png`,
  "produce.potato": `${ATLAS}/produce-potato.png`,
  "produce.carrot": `${ATLAS}/produce-carrot.png`,
  "produce.flax": `${ATLAS}/produce-flax.png`,
  "produce.apple": `${ATLAS}/produce-apple.png`,
  "produce.sunflower_seed": `${ATLAS}/produce-sunflower_seed.png`,
  "produce.olive": `${ATLAS}/produce-olive.png`,
} as const;

export type ProduceSpriteKey = keyof typeof UI_PRODUCE;

/** Growing crop portraits for the field inspection panel. */
export const UI_PLANTS = {
  "crop.wheat": `${ATLAS}/plant-wheat.png`,
  "crop.barley": `${ATLAS}/plant-barley.png`,
  "crop.corn": `${ATLAS}/plant-corn.png`,
  "crop.tomato": `${ATLAS}/plant-tomato.png`,
  "crop.potato": `${ATLAS}/plant-potato.png`,
  "crop.carrot": `${ATLAS}/plant-carrot.png`,
  "crop.flax": `${ATLAS}/plant-flax.png`,
  "crop.apple_tree": `${ATLAS}/plant-apple_tree.png`,
  "crop.sunflower": `${ATLAS}/plant-sunflower.png`,
  "crop.olive_tree": `${ATLAS}/plant-olive_tree.png`,
} as const;

export type PlantSpriteKey = keyof typeof UI_PLANTS;

/** Crop lifecycle stage badges. */
export const UI_GROWTH = {
  "seeded": `${ATLAS}/growth-seeded.png`,
  "growing": `${ATLAS}/growth-growing.png`,
  "mature": `${ATLAS}/growth-mature.png`,
  "withered": `${ATLAS}/growth-withered.png`,
} as const;

export type GrowthSpriteKey = keyof typeof UI_GROWTH;

/** Consumable supplies for fishing, farming and boats. */
export const UI_SUPPLIES = {
  "item.ground_grain": `${ATLAS}/item-ground_grain.png`,
  "item.bait_worms": `${ATLAS}/item-bait_worms.png`,
  "item.chum_bucket": `${ATLAS}/item-chum_bucket.png`,
  "item.basic_lure": `${ATLAS}/item-basic_lure.png`,
  "item.fish_scraps": `${ATLAS}/item-fish_scraps.png`,
  "item.basic_fertilizer": `${ATLAS}/item-basic_fertilizer.png`,
  "item.compost_starter": `${ATLAS}/item-compost_starter.png`,
  "item.plant_matter": `${ATLAS}/item-plant_matter.png`,
  "item.boat_fuel": `${ATLAS}/item-boat_fuel.png`,
  "item.crushed_ice": `${ATLAS}/item-crushed_ice.png`,
} as const;

export type SupplySpriteKey = keyof typeof UI_SUPPLIES;

/** Catch and produce quality medallions. */
export const UI_QUALITY = {
  "normal": `${ATLAS}/quality-normal.png`,
  "silver": `${ATLAS}/quality-silver.png`,
  "gold": `${ATLAS}/quality-gold.png`,
  "iridium": `${ATLAS}/quality-iridium.png`,
} as const;

export type QualitySpriteKey = keyof typeof UI_QUALITY;

/** Farm field-sign chips shown while the GIS overlay is held. */
export const UI_GIS = {
  "moist": `${ATLAS}/gis-moist.png`,
  "dry": `${ATLAS}/gis-dry.png`,
  "harvestReady": `${ATLAS}/gis-harvest-ready.png`,
  "growing": `${ATLAS}/gis-growing.png`,
  "prepared": `${ATLAS}/gis-prepared.png`,
} as const;

export type GisSpriteKey = keyof typeof UI_GIS;

/** NPC dialogue portraits. */
export const UI_PORTRAITS = {
  "npc.elspeth": `${ATLAS}/portrait-elspeth.png`,
  "npc.barnaby": `${ATLAS}/portrait-barnaby.png`,
  "npc.silas": `${ATLAS}/portrait-silas.png`,
  "npc.maeve": `${ATLAS}/portrait-maeve.png`,
  "npc.tomas": `${ATLAS}/portrait-tomas.png`,
  "npc.ines": `${ATLAS}/portrait-ines.png`,
} as const;

export type PortraitSpriteKey = keyof typeof UI_PORTRAITS;

/** Sky and sea condition icons for the almanac and forecast. */
export const UI_WEATHER = {
  "clear": `${ATLAS}/weather-clear.png`,
  "overcast": `${ATLAS}/weather-overcast.png`,
  "light-rain": `${ATLAS}/weather-light-rain.png`,
  "rain": `${ATLAS}/weather-rain.png`,
  "storm": `${ATLAS}/weather-storm.png`,
  "fog": `${ATLAS}/weather-fog.png`,
  "wind": `${ATLAS}/weather-wind.png`,
  "thermometer": `${ATLAS}/weather-thermometer.png`,
  "wave": `${ATLAS}/weather-wave.png`,
} as const;

export type WeatherSpriteKey = keyof typeof UI_WEATHER;

/** Time-of-day icons for the almanac dial. */
export const UI_TIME = {
  "sun": `${ATLAS}/time-sun.png`,
  "moon": `${ATLAS}/time-moon.png`,
  "dawn": `${ATLAS}/time-dawn.png`,
  "dusk": `${ATLAS}/time-dusk.png`,
} as const;

export type TimeSpriteKey = keyof typeof UI_TIME;

/** Tool belt icons. */
export const UI_TOOLS = {
  "hoe": `${ATLAS}/tool-hoe.png`,
  "watering_can": `${ATLAS}/tool-watering_can.png`,
  "bait": `${ATLAS}/tool-bait.png`,
  "rod": `${ATLAS}/tool-rod.png`,
  "pickaxe": `${ATLAS}/tool-pickaxe.png`,
  "basket": `${ATLAS}/tool-basket.png`,
} as const;

export type ToolSpriteKey = keyof typeof UI_TOOLS;

/** Fishing-rod progression icons for the equipped hotbar slot and Harbor Tackle. */
export const UI_RODS = {
  "rod.willow": `${ATLAS}/rod-willow.png`,
  "rod.river": `${ATLAS}/rod-river.png`,
  "rod.heavy_sport": `${ATLAS}/rod-heavy_sport.png`,
  "rod.offshore": `${ATLAS}/rod-offshore.png`,
  "rod.master": `${ATLAS}/rod-master.png`,
} as const;

export type RodSpriteKey = keyof typeof UI_RODS;

/** Navigation icons for modal headers and the pause menu. */
export const UI_MENU = {
  "backpack": `${ATLAS}/menu-backpack.png`,
  "journal": `${ATLAS}/menu-journal.png`,
  "ledger": `${ATLAS}/menu-ledger.png`,
  "compass": `${ATLAS}/menu-compass.png`,
  "expedition": `${ATLAS}/menu-expedition.png`,
  "menu": `${ATLAS}/menu-menu.png`,
} as const;

export type MenuSpriteKey = keyof typeof UI_MENU;

/** Purse, labour and alert icons. */
export const UI_STATUS = {
  "coin": `${ATLAS}/status-coin.png`,
  "labor": `${ATLAS}/status-labor.png`,
  "warning": `${ATLAS}/status-warning.png`,
} as const;

export type StatusSpriteKey = keyof typeof UI_STATUS;

/** Generic world-subject icons used as fallbacks. */
export const UI_WORLD = {
  "sprout": `${ATLAS}/world-sprout.png`,
  "fish": `${ATLAS}/world-fish.png`,
  "boat": `${ATLAS}/world-boat.png`,
} as const;

export type WorldSpriteKey = keyof typeof UI_WORLD;

/** Icons for the timed action progress bar. */
export const UI_ACTION = {
  "plant": `${ATLAS}/action-plant.png`,
  "water": `${ATLAS}/action-water.png`,
  "harvest": `${ATLAS}/action-harvest.png`,
  "processing": `${ATLAS}/action-processing.png`,
  "pickup": `${ATLAS}/action-pickup.png`,
  "place": `${ATLAS}/action-place.png`,
  "workstation": `${ATLAS}/action-workstation.png`,
  "cast": `${ATLAS}/action-cast.png`,
  "board": `${ATLAS}/action-board.png`,
  "dock": `${ATLAS}/action-dock.png`,
} as const;

export type ActionSpriteKey = keyof typeof UI_ACTION;

/** Hooked-fish behaviour cues in the sport fishing HUD. */
export const UI_BEHAVIOR = {
  "run": `${ATLAS}/behavior-run.png`,
  "dive": `${ATLAS}/behavior-dive.png`,
  "surface": `${ATLAS}/behavior-surface.png`,
  "burst": `${ATLAS}/behavior-burst.png`,
  "shake": `${ATLAS}/behavior-shake.png`,
  "tiring": `${ATLAS}/behavior-tiring.png`,
} as const;

export type BehaviorSpriteKey = keyof typeof UI_BEHAVIOR;

/** World map landmark markers. */
export const UI_MAP_NODES = {
  "homestead": `${ATLAS}/mapnode-homestead.png`,
  "garden": `${ATLAS}/mapnode-garden.png`,
  "village": `${ATLAS}/mapnode-village.png`,
  "river_crossing": `${ATLAS}/mapnode-river_crossing.png`,
  "river": `${ATLAS}/mapnode-river.png`,
  "harbor": `${ATLAS}/mapnode-harbor.png`,
  "lighthouse": `${ATLAS}/mapnode-lighthouse.png`,
  "offshore": `${ATLAS}/mapnode-offshore.png`,
  "sunreach": `${ATLAS}/mapnode-sunreach.png`,
} as const;

export type MapnodeSpriteKey = keyof typeof UI_MAP_NODES;

/** Panel ornament and trend indicators. */
export const UI_CHROME = {
  "demand_up": `${ATLAS}/chrome-demand_up.png`,
  "demand_down": `${ATLAS}/chrome-demand_down.png`,
  "corner_leaf": `${ATLAS}/chrome-corner_leaf.png`,
  "corner_rope": `${ATLAS}/chrome-corner_rope.png`,
} as const;

export type ChromeSpriteKey = keyof typeof UI_CHROME;

/** Seamless paper tile behind every panel. Copied whole, not keyed. */
export const UI_PARCHMENT_GRAIN = `${ATLAS}/parchment-grain.png`;

export const UI_ATLAS_SPRITE_COUNT = 158;
